spring.application.name=gep-back

spring.datasource.url=jdbc:postgresql://localhost:5432/gep-dev
spring.datasource.username=postgres
spring.datasource.password=pge1n9o8a0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true